
custom:
  dedupe:
    - twelve

functions:
  goodbye:
    handler: src/goodbye/index.goodbye

resources: 
  Resources:
    lambdaAccessPolicy:
      Properties:
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action: "lambda:invokeFunction"
              Resource:
                Fn::GetAtt: [ GoodbyeFunction, Arn ]

    carsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: carsTable
        AttributeDefinitions:
          - AttributeName: registration
            AttributeType: S
        KeySchema:
          - AttributeName: registration
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1