

custom:
  dedupe:
    - eleven

provider:
  environment:
    HELLO_ENV_VARIABLE: 'hi'

functions:
  hello:
    handler: src/hello/index.hello

resources: 
  Resources:
    lambdaAccessPolicy:
      Properties:
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Action: "lambda:invokeFunction"
              Resource:
                Fn::GetAtt: [ HelloFunction, Arn ]
   
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: registration
            AttributeType: S
        KeySchema:
          - AttributeName: registration
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1